# W&B Sweep Configuration
name: health_hyperparameter_sweep
project: lemurs-modeling
method: grid
metric:
  name: val/f1
  goal: maximize

parameters:
  # Sweep variables
  model_choice:
    values: [health, majority, lag, flaml]
  aggregator_choice:
    values: [suicide_risk, self_harm, negative_emotion, positive_emotion, emotion_regulation, minority_stress, social_connection, social_stress]
  sampler_choice:
    values: [block, daily, lag, offset, rolling_hour]
  
  split_mode_choice:
    values: [user, longitudinal]
  
command:
  - bash
  - scripts/sweep_wrapper.sh
  - ${args_no_hyphens}
