# W&B Sweep Configuration
name: regression_hyperparameter_sweep
project: lemurs-modeling
method: grid
metric:
  name: val/mse
  goal: minimize

parameters:
  data/aggregator:
    values: [positive_emotion_regression, self_harm_regression, suicide_risk_regression]
  data/scaler:
    values: [standard, subject_standard]
  data/sampler:
    values: [block, offset]
  ++data.sampler.resample_freq:
    values: [4h, 6h, 12h]
  data.os_filter:
    values: [ios, both]
  data.collapse_strategy:
    values: [mean, last, none]
  ++data.sampler.lookback_days:
    values: [3, 5, 7]
  ++data.sampler.start_offset_hours:
    values: [-72, -120, -168]

command:
  - python
  - src/train.py
  - "++data.sampler.end_offset_hours=0"
  - "data.modalities=[step]"
  - "data/preprocessors=[step]"
  - "trainer.max_epochs=75"
  - "callbacks=[regression_metrics,target_distribution]"
  - "logger.wandb.group=regression_sweep"
  - "logger=[csv,wandb]"
  - "model=regression"
  - ${args_no_hyphens}
