# @package _global_

defaults:
  - _self_
  - data: default
  - model: default
  - logger: csv
  - trainer: cpu
  - paths: default
  - extras: default
  - hydra: default
  - callbacks: [classification_metrics]

task_name: "test"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???

# seed for random number generators in pytorch, numpy and python.random
seed: null
