_target_: src.models.components.simple_lstm.SimpleLSTM
input_size: ${len:${data.modalities}}
hidden_size: 64
num_layers: 2
dropout: 0.1
use_user_embedding: ${model.use_subject_embedding}
use_sequence_data: ${model.use_sequence_data}
use_prev_prediction: ${model.use_prev_prediction}
output_size: ${oc.select:data.aggregator.num_classes,2}